name: 'Amplify PR Preview'
on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Comment PR preview URL
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Preview build: https://${{ github.head_ref }}.${{ secrets.AMPLIFYAPPID }}.amplifyapp.com/
        comment_tag: preview_comment_tag