name: Test env deploy

on:
  pull_request:
    branches: ["master"]

permissions:
  pull-requests: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Ruff check
        run: ruff .

      - name: Mypy check
        run: mypy .
  aws_cdk_test_deploy:
    name: CDK Test Deployment
    needs: [tests]
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-2"

      - name: Synth Dev stack
        run: cdk synth dev-env/ApiKeyServiceStack

      - name: Deploy Dev stack
        run: cdk deploy dev-env/ApiKeyServiceStack --require-approval never
