name: Test env deploy

on:
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write

jobs:
  pre-checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Ruff check
        run: ruff .

      - name: Mypy check
        run: mypy .
  unit-test:
    name: 'Unit tests - Localstack'
    runs-on: ubuntu-latest
    env:
      CDK_REGION: eu-west-2
      CDK_ACCOUNT: 000000000000
      STACK_NAME: dev-env/ApiKeyServiceStac
    steps:
      - uses: actions/checkout@v4
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
          install-awslocal: 'true'

      - name: Setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.11

      - name: Install aws-cdk-local
        run: npm install -g aws-cdk-local aws-cdk

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run deploy script for local
        run: ./scripts/deploy.sh dev --local

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: 'src/go.sum'


      - name: Run unit tests
        run: go test ./src/lambdas/...
  aws_cdk_test_deploy:
    name: CDK Test Deployment
    needs: [pre-checks, unit-test]
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.11

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-2"

      - name: Run deploy script
        run: ./scripts/deploy.sh Dev
